### ISSUE TITLE
Not searchable

### ISSUE THREAD

**Issue by SMcCandlish** [rmcgirr83/topicdescription#4]
The built-in search function matches only titles and message bodies. It would be ideal if it also matched Description content.  An example use case: Gardening site. Posts about plants use the scientific name as the post title. Common (vernacular) names go in Description (and for some plants there might be 10 of them).  A search for a common name should find the right article by matching the hit in the Description field.

There some more detailed discussion of this and a related request at: [https://www.phpbb.com/customise/db/extension/topic_description/support/topic/221271](https://www.phpbb.com/customise/db/extension/topic_description/support/topic/221271)

**Comment by rmcgirr83** [comment]
There are no events prior to the updating the search index for the topic description to be added. There is one but it would mess up the topic title/subject. Nothing I can do about that, sorry.
